<?php

/**
 * ขอบเขต/ประเภทงานต่อบริการ — key ตาม slug ใน DB
 * group: included | type | warranty | cert
 */
return [
    'building-demolish' => [
        ['name' => 'สำรวจและประเมินหน้างาน', 'group' => 'included'],
        ['name' => 'ตัดไฟ ตัดน้ำ และเตรียมพื้นที่', 'group' => 'included'],
        ['name' => 'รื้อถอนโครงสร้างตามแผน', 'group' => 'included'],
        ['name' => 'ขนเศษวัสดุออกทิ้งถูกต้อง', 'group' => 'included'],
        ['name' => 'รื้อถอนอาคารคอนกรีต', 'group' => 'type'],
        ['name' => 'รื้อถอนอาคารโครงเหล็ก', 'group' => 'type'],
        ['name' => 'ทำความสะอาดและส่งมอบพื้นที่', 'group' => 'included'],
        ['name' => 'รายงานปริมาณงานและ BOQ', 'group' => 'included'],
    ],
    'pile' => [
        ['name' => 'สำรวจสภาพดินหน้างาน', 'group' => 'included'],
        ['name' => 'ออกแบบและคำนวณฐานราก', 'group' => 'included'],
        ['name' => 'กดเสาเข็มไมโครไพล์ (Micropile)', 'group' => 'type'],
        ['name' => 'กดเสาเข็ม I-Shape / หกเหลี่ยม', 'group' => 'type'],
        ['name' => 'ทดสอบและรายงานผลการกด', 'group' => 'included'],
        ['name' => 'ใบรับรองวิศวกร (กว.)', 'group' => 'cert'],
        ['name' => 'ทำความสะอาดหน้างาน', 'group' => 'included'],
        ['name' => 'รับประกันงานฐานราก', 'group' => 'warranty'],
    ],
    'excavator' => [
        ['name' => 'รถแม็คโครขนาดเล็ก–ใหญ่', 'group' => 'type'],
        ['name' => 'งานขุด ถม และเคลียร์พื้นที่', 'group' => 'included'],
        ['name' => 'งานรื้อถอนอาคาร', 'group' => 'type'],
        ['name' => 'หัวเจาะ / หัวแย็ก', 'group' => 'type'],
        ['name' => 'งานกดเสาเข็มหน้างาน', 'group' => 'type'],
        ['name' => 'พร้อมคนขับมืออาชีพ', 'group' => 'included'],
        ['name' => 'เช่ารายวัน / รายเดือน', 'group' => 'type'],
        ['name' => 'บริการครอบคลุม กทม. และปริมณฑล', 'group' => 'included'],
    ],
    'landfill' => [
        ['name' => 'สำรวจระดับและออกแบบการถม', 'group' => 'included'],
        ['name' => 'ถมดิน / ถมทราย / ถมลูกรัง', 'group' => 'type'],
        ['name' => 'บดอัดทุก 30 ซม. ตามมาตรฐาน', 'group' => 'included'],
        ['name' => 'รถแบคโฮ รถบด รถดัมพ์', 'group' => 'included'],
        ['name' => 'ดูดทราย (Sand Pump) พื้นที่แคบ', 'group' => 'type'],
        ['name' => 'ปรับระดับพื้นและวัดเกรด', 'group' => 'included'],
        ['name' => 'นำดินหรือวัสดุเก่าออกทิ้ง', 'group' => 'included'],
        ['name' => 'ใบรับรองปริมาณดินถมจริง', 'group' => 'cert'],
    ],
    'shipment' => [
        ['name' => 'ขนเศษวัสดุก่อสร้าง', 'group' => 'included'],
        ['name' => 'ขนดิน ขนหิน ขนทราย', 'group' => 'type'],
        ['name' => 'รถ 6 ล้อ / 10 ล้อ', 'group' => 'type'],
        ['name' => 'ทิ้งถูกต้องตามกฎหมาย', 'group' => 'included'],
        ['name' => 'รับ-ส่งตรงเวลา', 'group' => 'included'],
        ['name' => 'BOQ และใบเสนอราคาชัดเจน', 'group' => 'included'],
        ['name' => 'ครอบคลุม กทม. และปริมณฑล', 'group' => 'included'],
        ['name' => 'บริการหกล้อครบวงจร', 'group' => 'included'],
    ],
    'demolish' => [
        ['name' => 'สำรวจและประเมินมูลค่าไม้', 'group' => 'included'],
        ['name' => 'รื้อถอนบ้านไม้เก่า', 'group' => 'included'],
        ['name' => 'ซื้อไม้เก่าราคาดี', 'group' => 'type'],
        ['name' => 'เคลียร์พื้นที่หลังรื้อถอน', 'group' => 'included'],
        ['name' => 'ขนเศษวัสดุออกทิ้ง', 'group' => 'included'],
        ['name' => 'ทำความสะอาดหน้างาน', 'group' => 'included'],
        ['name' => 'ทีมช่างมืออาชีพ', 'group' => 'included'],
        ['name' => 'ประสบการณ์สูง', 'group' => 'included'],
    ],
    'clearforest' => [
        ['name' => 'สำรวจพื้นที่และประเมินปริมาณ', 'group' => 'included'],
        ['name' => 'ถางป่าและตัดต้นไม้', 'group' => 'included'],
        ['name' => 'ขุดตอและเคลียร์วัชพืช', 'group' => 'included'],
        ['name' => 'ขนเศษออกทิ้ง', 'group' => 'included'],
        ['name' => 'ปรับพื้นที่เบื้องต้น', 'group' => 'included'],
        ['name' => 'รถแบคโฮและเครื่องจักร', 'group' => 'included'],
        ['name' => 'งานครบวงจร', 'group' => 'included'],
        ['name' => 'ราคาถูก คุ้มค่า', 'group' => 'included'],
    ],
    'landjustment' => [
        ['name' => 'สำรวจระดับและออกแบบการปรับพื้น', 'group' => 'included'],
        ['name' => 'ไถปรับที่ดิน', 'group' => 'type'],
        ['name' => 'ปรับหน้าดินและวัดเกรด', 'group' => 'included'],
        ['name' => 'รถแบคโฮและเครื่องจักร', 'group' => 'included'],
        ['name' => 'งานสวน ไร่นา และก่อสร้าง', 'group' => 'type'],
        ['name' => 'ถมดินและบดอัด', 'group' => 'type'],
        ['name' => 'ทีมงานมืออาชีพ', 'group' => 'included'],
        ['name' => 'ประเมินราคาเบื้องต้นฟรี', 'group' => 'included'],
    ],
    'waste' => [
        ['name' => 'สำรวจและออกแบบระบบ', 'group' => 'included'],
        ['name' => 'วางถังบำบัดน้ำเสีย (Septic Tank)', 'group' => 'type'],
        ['name' => 'ระบบบำบัดตามมาตรฐาน', 'group' => 'included'],
        ['name' => 'ติดตั้งปั๊มและระบบท่อ', 'group' => 'included'],
        ['name' => 'ทดสอบระบบก่อนส่งมอบ', 'group' => 'included'],
        ['name' => 'งานบ้านและอาคาร', 'group' => 'type'],
        ['name' => 'ทำความสะอาดหน้างาน', 'group' => 'included'],
        ['name' => 'บริการครบวงจร', 'group' => 'included'],
    ],
    'retaining-wall' => [
        ['name' => 'สำรวจและออกแบบโครงสร้าง', 'group' => 'included'],
        ['name' => 'คำนวณโดยวิศวกรโยธา', 'group' => 'included'],
        ['name' => 'เข็มเจาะ หรือเข็มตอก', 'group' => 'included'],
        ['name' => 'เทคอนกรีตเสริมเหล็ก', 'group' => 'included'],
        ['name' => 'ระบบระบายน้ำหลังกำแพง', 'group' => 'included'],
        ['name' => 'ใบรับรองวิศวกร (กว.)', 'group' => 'cert'],
        ['name' => 'ทำความสะอาดหน้างาน', 'group' => 'included'],
        ['name' => 'รับประกันโครงสร้าง 2 ปี', 'group' => 'warranty'],
    ],
    'garden-plot' => [
        ['name' => 'ออกแบบร่องสวนตามแปลง', 'group' => 'included'],
        ['name' => 'ขุดร่องสวนทุกขนาด', 'group' => 'included'],
        ['name' => 'ปรับระดับและวางแนว', 'group' => 'included'],
        ['name' => 'วางท่อรดน้ำ (ถ้าต้องการ)', 'group' => 'type'],
        ['name' => 'ถมดินปลูกและเก็บงาน', 'group' => 'included'],
        ['name' => 'ทีมช่างมืออาชีพ', 'group' => 'included'],
        ['name' => 'ราคาประหยัด', 'group' => 'included'],
        ['name' => 'บริการครบวงจร', 'group' => 'included'],
    ],
    'footing' => [
        ['name' => 'สำรวจและออกแบบฐานราก', 'group' => 'included'],
        ['name' => 'ขุดหลุมฟุตติ้ง', 'group' => 'included'],
        ['name' => 'วางเหล็กเสริมตามแบบ', 'group' => 'included'],
        ['name' => 'เทคอนกรีตฟุตติ้งและตอม่อ', 'group' => 'included'],
        ['name' => 'ปรับระดับด้วยเลเซอร์', 'group' => 'included'],
        ['name' => 'งานคาน เสา แผ่นพื้น', 'group' => 'type'],
        ['name' => 'ทำความสะอาดหน้างาน', 'group' => 'included'],
        ['name' => 'รับประกันงานโครงสร้าง', 'group' => 'warranty'],
    ],
    'truck' => [
        ['name' => 'รถ 6 ล้อพร้อมคนขับ', 'group' => 'included'],
        ['name' => 'เช่ารายวัน / รายเดือน', 'group' => 'type'],
        ['name' => 'ขนดิน ขนเศษ ขนวัสดุ', 'group' => 'type'],
        ['name' => 'ราคาดีที่สุด', 'group' => 'included'],
        ['name' => 'บริการครอบคลุม กทม. และปริมณฑล', 'group' => 'included'],
        ['name' => 'BOQ ชัดเจน', 'group' => 'included'],
        ['name' => 'ตรงเวลา ไว้ใจได้', 'group' => 'included'],
        ['name' => 'บริการเช่ารถบรรทุกครบวงจร', 'group' => 'included'],
    ],
    'pipe' => [
        ['name' => 'สำรวจและออกแบบเส้นทางน้ำ', 'group' => 'included'],
        ['name' => 'ขุดร่องวางท่อ PVC / คอนกรีต', 'group' => 'included'],
        ['name' => 'บ่อพัก (Manhole) ตามระยะ', 'group' => 'included'],
        ['name' => 'บ่อดักไขมัน Grease Trap', 'group' => 'type'],
        ['name' => 'Sump Pit + ปั๊มน้ำ', 'group' => 'type'],
        ['name' => 'ท่อรางสำเร็จรูป ACO', 'group' => 'type'],
        ['name' => 'ฝังกลบและบดอัดคืน', 'group' => 'included'],
        ['name' => 'ทดสอบการไหลน้ำก่อนส่งมอบ', 'group' => 'included'],
    ],
    'dam' => [
        ['name' => 'สำรวจสภาพดินและระดับน้ำ', 'group' => 'included'],
        ['name' => 'ออกแบบและคำนวณโครงสร้าง', 'group' => 'included'],
        ['name' => 'งานฐานราก เข็มเจาะ/เข็มตอก', 'group' => 'included'],
        ['name' => 'เหล็กเสริมตามแบบ มอก.', 'group' => 'included'],
        ['name' => 'เทคอนกรีตกำลังอัดตามสเปก', 'group' => 'included'],
        ['name' => 'ระบบระบายน้ำ (Weep hole)', 'group' => 'included'],
        ['name' => 'ถมกลับและบดอัด', 'group' => 'included'],
        ['name' => 'เก็บงานผิวและทำความสะอาดหน้างาน', 'group' => 'included'],
    ],
    'pour-concrete' => [
        ['name' => 'ปรับระดับและบดอัดพื้น', 'group' => 'included'],
        ['name' => 'วางทรายและแผ่นกันชื้น', 'group' => 'included'],
        ['name' => 'เหล็กตะแกรง Wire mesh', 'group' => 'included'],
        ['name' => 'เทคอนกรีตและปรับระดับ', 'group' => 'included'],
        ['name' => 'ขัดมัน / ขัดเงา (ถ้าเลือก)', 'group' => 'type'],
        ['name' => 'ตัดร่อง Joint', 'group' => 'included'],
        ['name' => 'เคลือบกันคราบ (ถ้าเลือก)', 'group' => 'type'],
        ['name' => 'รับประกันพื้นผิว', 'group' => 'warranty'],
    ],
    'fence' => [
        ['name' => 'รั้วก่ออิฐมอญ / บล็อกปูน', 'group' => 'type'],
        ['name' => 'รั้วสำเร็จรูป Precast', 'group' => 'type'],
        ['name' => 'รั้วโมเดิร์น ลายทาง / ช่องอากาศ', 'group' => 'type'],
        ['name' => 'รั้วเหล็กดัด / เหล็กโปร่ง', 'group' => 'type'],
        ['name' => 'ประตูบานเลื่อน / บานสวิง + รีโมท', 'group' => 'type'],
        ['name' => 'ทาสีภายนอก + สีกันซึม', 'group' => 'included'],
        ['name' => 'งานลวดหนาม / ลวดตาข่าย', 'group' => 'type'],
        ['name' => 'รับประกันงาน 2 ปี', 'group' => 'warranty'],
    ],
];
